version: '3.7'

services:
  deno:
    container_name: deno
    image: ${REGISTRY:-deno}/deno:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: .docker/deno.dockerfile
    depends_on:
      - deno-data
    networks:
      - deno_api
    ports:
      - "1447:1447"
    command: bash -c "deno run --allow-net src/main.ts"

  deno-data:
    image: postgres:11.5
    networks:
      - deno_api
    container_name: deno-data
    volumes:
      - deno_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user
      - PGDATA=/var/lib/postgresql/data/pgdata

networks:
  deno_api:

volumes:
  deno_data: {}
